export enum ProductCategory {
  UNKNOWN = 'UNKNOWN',
  PERFUMES = 'PERFUMES',
  COSMETICS = 'COSMETICS',
  SKINCARE = 'SKINCARE',
  HAIRCARE = 'HAIRCARE',
  ELECTRONICS = 'ELECTRONICS',
  CLOTHING = 'CLOTHING',
  ACCESSORIES = 'ACCESSORIES',
  HOME = 'HOME',
  FOOD = 'FOOD',
  BEVERAGES = 'BEVERAGES',
  SPORTS = 'SPORTS',
  BOOKS = 'BOOKS',
  TOYS = 'TOYS',
  OTHER = 'OTHER',
}

